apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
  labels:
    group: example-app
spec:
  replicas: 1
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [first-app] }
  template:
    metadata:
      labels:
        app: first-app
        tier: backend
    spec:
      containers:
        - name: first-nodejs-app
          image: thomascode92/kub-first-app:latest
