apiVersion: v1
kind: Service
metadata:
  name: first-app-service
  labels:
    group: example-app
spec:
  selector:
    app: first-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
