services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
    networks:
      - goals-net
    container_name: mongodb
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    networks:
      - goals-net
    container_name: goals-backend
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    networks:
      - goals-net
    container_name: goals-frontend

volumes:
  data:
  logs:

networks:
  goals-net:
