services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongodb.env
    networks:
      - goals-net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    networks:
      - goals-net
    depends_on:
      - mongodb

  # frontend:

volumes:
  data:
  logs:

networks:
  goals-net:
